### ISSUE TITLE
Chainmail armor giving resistance to projectiles makes no sense at all.

### ISSUE THREAD

**Issue by Stitch3s712** [CammiePone/Planning-Docs#1]
It's useless against arrows and bolts.

**Comment by CammiePone** [comment]
Giving it anything else useful makes just as little sense. Minecraft isn't set in reality.

**Comment by Stitch3s712** [comment]
It's useful against slashing damage, so you could give it bonus resistance against swords. And while Minecraft isn't set in reality, the concept of chainmail armor has its roots in real life, so it has to be somewhat realistic.

**Comment by CammiePone** [comment]
Being limited by reality is dumb, and adding a resistance for a damage type that doesn't exist is a pain in the ass.

**Comment by Stitch3s712** [comment]
It's not being "limited by reality". That's just how game design works... If a game isn't something too supernatural and has some elements that have their roots in real life, those elements have to have the general behavior of their real life counterparts. Water for example has the basic function of saving you from fall damage. The only thing is that the degree of realism is toned down, so it can even save you from unlimited heights. But the general behavior is there, and the same should apply to chain mail armor in this mod. It doesn't even make moderately sense that it gives projectile protection, because that's the thing it's really bad at. You don't even really have to know what it looks like in real life and how it operates in real life. Just look at the textures... it has holes in it. Holes which projectiles can go through very easily. And just because it's a pain in the ass to do it that doesn't mean you shouldn't do it. I mean I don't know what your life situation is right now, but if you're gonna make a mod you have to do it properly, else, what's the point of making it in the first place?

**Comment by CammiePone** [comment]
First off, by pain in the ass, I mean its function will be inconsistent. There's plenty of weapons that are swords in the code that are clearly meant to be piercing weapons. You would end up with the function acting when it shouldn't, and not acting when it should. Insistency is far worse.

Secondly, there is no "proper" way to make a mod. Mod devs can do whatever they want with their mods because they're the ones who spend the time to make them and release them for free.

Thirdly, there's a reason the armour resistances haven't been added to the mod yet. I'm not happy with them, and I'm unsure the best way to go about them.

**Comment by Stitch3s712** [comment]
Hmm I didn't know that thing about the code...

Yeah but I'm saying that from a game design perspective, since Minecraft doesn't stray too far from reality for being a fantasy game, it should have *some* realism, which it already does, so overhaul- and enhancing-type mods should follow the same principle.

So it *isn't* in the mod yet? I thought it was...
So what kind of resistance are you thinking of? Do you just want to give different armor types different bonuses like they are now, or overhaul the armor system as a whole?

**Comment by CammiePone** [comment]
I would like to overhaul the armour system as a whole, but I also need it to be compatible with modded armours and enchantments, which causes so many headaches.

**Comment by Stitch3s712** [comment]
Do you already have a few ideas? And would those ideas require an overhaul of the damage system too? (including mob damage and all that)

One idea would be just giving all armor multiplicative protection. Additive protection is very hard to balance, but if you're up for the challenge, use a different method.

Multiplicative protection would be nice since it basically flattens out the difficulty more than additive armor. While it will be more effective against strong attacks (but you'll still take a whole lot of damage), weaker enemies will still do a bit of damage since their attack wasn't strong to begin with. This way you can prevent the player from becoming too strong, so he still has to be careful, even with weaker mobs.
80% protection with full Netherite armor sounds reasonable I guess, but that should be the absolute max for Netherite. You can't forget about enchantments either. 
The problem with this would be support for stronger modded materials, since, if you give Netherite 80%, there's support for only about 3 better materials, depending on how much stronger they are, and maybe a 4th OP material that cold have 99% protection.
Otherwise, this should be the easiest out of all possible solutions.

Anyways, for modding compatibility, instead of adjusting your own mod *to* them, you could make addons for your main mod that add compatibility for other mods that remove, add or change those mods' conflicting behaviors. 
Most people are just looking for a good mod that overhauls the existing combat, and they don't care much about extra ores and additional sets of tools.

**Comment by CammiePone** [comment]
I personally dislike multiplicative damage reduction, which is what vanilla already does. 80% reduction for Netherite is also pretty close to what enchanted netherite caps out on, while enchanted netherite gets about 96% reduction.

**Comment by Stitch3s712** [comment]
Well the thing with vanilla is that it's first off random, and second it's only *kind of* multiplicative, from what I read on the wiki.

And why do you dislike it, exactly?

**Comment by CammiePone** [comment]
Vanilla's isn't random, and it is fully multiplicative, but it follows a curve. Higher damage sources get reduced less than lower damage sources.

And idk, I just never liked it in games. I much preferred things like damage threshold and giving armour piercing to weapons, and I'm thinking I might do that, while also bringing back toughness as a thing that reduces armour piercing damage.

Maybe something like this for armour itself:
```java
actualDamage = Math.max(0, damage - (armor * 0.25)) + Math.max(0, piercingDamage * (toughness * 0.05));
```
---
That way, hitting someone in full unenchanted Netherite with a Sharpness V Netherite Sword that deals 8 normal damage and 3 armour piercing damage without a crit would deal 3.8 damage, which is actually only a little higher than the 3.2 damage that would deal in Vanilla.

I'd still have to rework the protection enchants.

**Comment by CammiePone** [comment]
Not sure. Might make a change to multishot to make the arrows deal less damage, and also nerf the power enchant

**Comment by Stitch3s712** [comment]
So you're gonna nerf an already bad weapon........

**Comment by Stitch3s712** [comment]
Multishot is *already* horrible. It takes 3 durability.

**Comment by CammiePone** [comment]
I don't think it does? Does it? If it does, then uhhh I don't think you realise how busted Multishot in CCT is. It does 33 damage up close, which is 8 more damage than power 5.
